### PR TITLE
SM-51 add maven checkstyle

### PR DESCRIPTION
**Pull request by santoshgaikwad14**
- Added Checkstyle configuration.
- Fixed all checkstyle suggestions.

### CODE REVIEW

**Comment by ankit11088** [comment]
@santoshgaikwad14 Can you get your branch updated with main first?? I think this merge will overwrite some other changes.

**Comment by ankit11088** [comment]
How does the checkstyle gets activated?

**Comment by santoshgaikwad14** [comment]
> How does the checkstyle gets activated?

It will get activated when we build our project with `mvn` command.

**Comment by santoshgaikwad14** [comment]
> @santoshgaikwad14 Can you get your branch updated with main first?? I think this merge will overwrite some other changes.

I merged latest `main` branch changes to my branch and its up o date. It include your last changes regarding Entity classes.

**Review by ankit11088 — APPROVED** [review]
Keeping it approved with suggestions.

**Pull request closed without merging**
